[561351][Richtext] Asynchronous set / save and load issues
eclipse/kitalpha pull request #62
Opened 2020-08-24 06:51 UTC by minhtutonthat

The actual solution gives side-effects on Windows event (e.g. unexpected
double click event). This patch provides a way to detect if the editor
is still loading its content.

Bug: 561351

Change-Id: I4b76305f518abacabbc11779367cabddefefdbc9
Signed-off-by: Tu Ton <minhtutonthat@gmail.com>

2020-08-24 11:55 UTC, sandupostaru requested changes

2020-08-24 11:55 UTC, sandupostaru commented on richtext/plugins/org.polarsys.kitalpha.richtext.common/src/org/polarsys/kitalpha/richtext/common/impl/AbstractMDERichTextWidget.java
> +  private boolean isLoading = false;
Formatting should be fixed.
This project uses tabs :(

2020-08-24 11:55 UTC, sandupostaru commented on richtext/plugins/org.polarsys.kitalpha.richtext.widget/src/org/polarsys/kitalpha/richtext/widget/internal/ListenerInstaller.java
> +          new Status(IStatus.WARNING, Activator.PLUGIN_ID, "Rich text widget cannot install testChangeEvent handler")); //$NON-NLS-1$
data ready event

2020-08-25 15:21 UTC, tguiu approved these changes

2020-08-25 15:22 UTC, merged