[releng] TP org.eclipse.core.runtime
eclipse/kitalpha pull request #676
Opened 2021-07-08 15:09 UTC by arnauddieumegard

Change-Id: Ie38223d08df34f114d51ed18a2418244f28b04cc

2021-07-28 14:28 UTC, bzendagui commented on .project
> +			</arguments>
test

2021-07-28 14:31 UTC, bzendagui commented on .project
>  	<projects>
It this file important? if not, can you remove it please?

2021-07-28 15:13 UTC, bzendagui requested changes
Can you please check all comment, there are some suggestions that we can discuss.

2021-07-28 15:13 UTC, bzendagui commented on massactions/tests/plugins/org.polarsys.kitalpha.massactions.junit.tests/tests/org/polarsys/kitalpha/massactions/tests/ju/test/view/ColumnHideShowTest.java
> +    Set<Integer> afterHiddenColumns;
To make the code easier to read and understund, can you please remove the declaration of the two sets from here and do them in the lines 118 and 124 (when the instances are created).

2021-07-29 08:20 UTC, arnauddieumegard commented on massactions/plugins/org.polarsys.kitalpha.massactions.core/src/org/polarsys/kitalpha/massactions/core/table/layer/body/MAColumnReorderLayer.java
> +        MutableIntList prevColumnIndexOrder = IntLists.mutable.empty();
I don't think so, previously used ArrayList<Integer> is not automatically sorted so the order was kept. MutableIntList have the same behavior (insertion order kept). This prevColumnIndexOrder variable is local and only stores the order.

2021-07-30 12:33 UTC, pdulth commented
Hi arnaud, 
We have updated the pipeline library, the api token was not the same for capella and kitalpha
https://github.com/eclipse/capella-pipeline-library/commit/3b6495f8319daa6c06e72ce329a0d160b1fd3416#diff-f9211705ca997c0414d44eddb3f7b0e97d7005e3848c38cb5c36ad94927c3e17R20-R23

2021-07-30 12:34 UTC, pdulth commented
current build shall be ok

2021-07-30 12:35 UTC, arnauddieumegard commented
> 
> 
> Hi arnaud,
> We have updated the pipeline library, the api token was not the same for capella and kitalpha
> [eclipse/capella-pipeline-library@3b6495f#diff-f9211705ca997c0414d44eddb3f7b0e97d7005e3848c38cb5c36ad94927c3e17R20-R23](https://github.com/eclipse/capella-pipeline-library/commit/3b6495f8319daa6c06e72ce329a0d160b1fd3416#diff-f9211705ca997c0414d44eddb3f7b0e97d7005e3848c38cb5c36ad94927c3e17R20-R23)

Thanks a lot !

2021-07-30 12:40 UTC, arnauddieumegard commented
> 
> 
> current build shall be ok

I'm afraid it will not, I think the calls to `github.build***Label(label)` will also fail.

2021-07-30 12:42 UTC, bzendagui commented
> > current build shall be ok
> 
> I'm afraid it will not, I think the calls to `github.build***Label(label)` will also fail.

If there are other issues, please revert the commit of the integration of the capella pipeline library. We will integrate it later.

2021-07-30 13:30 UTC, arnauddieumegard commented
> 
> 
> > > current build shall be ok
> > 
> > 
> > I'm afraid it will not, I think the calls to `github.build***Label(label)` will also fail.
> 
> If there are other issues, please revert the commit of the integration of the capella pipeline library. We will integrate it later.

It is indeed more complex, it requires to:
- modify the pipeline-library code for label and messages
- publish the PR result on the download.eclipse.org website or link to the product in the ci instance in the generated message

2021-07-30 13:42 UTC, pdulth commented
yes, maybe merge it like that, or without the commit with pipeline, in order to have a capella 6.0 with correct nattable and richtext that we can deliver for Team4Capella, then we will think on how we can commonalize all the chain

2021-07-30 14:26 UTC, merged